### PR TITLE
feat: make build with rollup (multiversional to support ES5)

### PR DESCRIPTION
**Pull request by xobotyi**
Due to need to support ie11 in `react-hooks` [issue](https://github.com/streamich/react-use/issues/575) I've made multiversional build via rollup;

### CODE REVIEW

**Comment by leepowelldev** [comment]
@streamich - are there any plans to merge these changes and support IE11? If not then we're going to have to remove react-use from our codebase.

**Comment by syabro** [comment]
@streamich давай замержим? `react-use` тоже получается сломан в ie11

**Review by streamich — APPROVED** [review]
Thanks!

**Pull request merged**
